//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFS.SpheresRiskPerformance.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOriginalTradeLoading {
            get {
                return ((bool)(this["UseOriginalTradeLoading"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimsPositionExtendedReport {
            get {
                return ((bool)(this["TimsPositionExtendedReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PositionExtendedReport {
            get {
                return ((bool)(this["PositionExtendedReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EurexPremiumFactorsReport {
            get {
                return ((bool)(this["EurexPremiumFactorsReport"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EurexAdditionalExchRateReport {
            get {
                return ((bool)(this["EurexAdditionalExchRateReport"]));
            }
            set {
                this["EurexAdditionalExchRateReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOriginalCalculationSheetSerialization {
            get {
                return ((bool)(this["UseOriginalCalculationSheetSerialization"]));
            }
            set {
                this["UseOriginalCalculationSheetSerialization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EurexAdditionalContractFactorsReport {
            get {
                return ((bool)(this["EurexAdditionalContractFactorsReport"]));
            }
            set {
                this["EurexAdditionalContractFactorsReport"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SVR-MSS-2\\SVRMSS2;Initial Catalog=RD_SPHERES_TST260;Persist Security " +
            "Info=True;User ID=sa")]
        public string RD_SPHERES_TST260ConnectionString1 {
            get {
                return ((string)(this["RD_SPHERES_TST260ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string EurosysReportPath {
            get {
                return ((string)(this["EurosysReportPath"]));
            }
            set {
                this["EurosysReportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.")]
        public string EurosysSchemaPrefix {
            get {
                return ((string)(this["EurosysSchemaPrefix"]));
            }
            set {
                this["EurosysSchemaPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsRoundedCashBalance {
            get {
                return ((bool)(this["IsRoundedCashBalance"]));
            }
            set {
                this["IsRoundedCashBalance"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DataValueMode {
            get {
                return ((bool)(this["DataValueMode"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCashPaymentFromCashBalanceForInterest {
            get {
                return ((bool)(this["IsCashPaymentFromCashBalanceForInterest"]));
            }
            set {
                this["IsCashPaymentFromCashBalanceForInterest"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateMaterializedView {
            get {
                return ((bool)(this["CreateMaterializedView"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataReaderMode {
            get {
                return ((bool)(this["DataReaderMode"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VerifyUnchangedCashBalance {
            get {
                return ((bool)(this["VerifyUnchangedCashBalance"]));
            }
            set {
                this["VerifyUnchangedCashBalance"] = value;
            }
        }
    }
}
