//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace EFS.SpheresIO.MarketData.T7RDF.v10
{


    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", IsNullable = false)]
    public partial class FIXML
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Batch", typeof(Batch_t))]
        [System.Xml.Serialization.XmlElementAttribute("Message", typeof(Abstract_message_t))]
        public object[] Items;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string v;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string r;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string xv;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string xr;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cv;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string s;

        public FIXML()
        {
            this.v = "FIX.5.0SP2";
            this.s = "2012-04-23";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class Batch_t
    {

        [System.Xml.Serialization.XmlElementAttribute("Hdr")]
        public BatchHeader_t Hdr;
                
        
        [System.Xml.Serialization.XmlElementAttribute("MktDef", typeof(MarketDefinition_message_t))]
        [System.Xml.Serialization.XmlElementAttribute("SecDef", typeof(SecurityDefinition_message_t))]
        [System.Xml.Serialization.XmlElementAttribute("SecStat", typeof(SecurityStatus_message_t))]
        [System.Xml.Serialization.XmlElementAttribute("SecDefUpd", typeof(SecurityDefinitionUpdateReport_message_t))]
        public Abstract_message_t[] Message;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string TotMsg;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class BatchHeader_t : BaseHeader_t
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BatchHeader_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageHeader_t))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class BaseHeader_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SID;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class ClearingPriceParameters_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessDayTypeEnum BizDayTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ClrPxOfst;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClrPxOfstSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string VegaMult;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string AnnlTrdgBizDays;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string TotTrdgBizDays;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string TrdgBizDays;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal StdVarnc;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StdVarncSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ReltdClsPx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReltdClsPxSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal RlzdVarnc;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RlzdVarncSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal RFR;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RFRSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal DiscFctr;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscFctrSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ARMVM;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ARMVMSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal OvrNiteIntRt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OvrNiteIntRtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Vol;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SetPx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SetPxSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CalculationMethodEnum CalcMeth;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CalcMethSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string AnnlClndrDays;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string RemClndrDays;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal CurPmtPrm;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurPmtPrmSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal AcrdPmtPrm;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcrdPmtPrmSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal RelNdxVal;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelNdxValSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal CurColtnPrm;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurColtnPrmSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal AcrdColtnPrm;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcrdColtnPrmSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class SecurityTradingRules_Block_t
    {

        /// <remarks/>
        public BaseTrdgRules_Block_t BaseTrdgRules;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class BaseTrdgRules_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TickRules")]
        public TickRules_Block_t[] TickRules;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QuotSzRules")]
        public QuoteSizeRules_Block_t[] QuotSzRules;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PxRngRules")]
        public PxRngRules_Block_t[] PxRngRules;

        /// <remarks/>
        public AuctTypRules_Block_t AuctTypRule;

        /// <remarks/>
        public TrdgSesRules_Block_t TrdgSesRules;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QuoteSideIndicatorEnum QuotSideInd;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuotSideIndSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QuoteSideModelTypeEnum QuotSideModelTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuotSideModelTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal FastMktPctg;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FastMktPctgSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MultilegModelEnum MlegModel;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MlegModelSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ImpliedMarketIndicatorEnum ImpldMktInd;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImpldMktIndSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PostTradeAnonymityEnum PostTrdAnon;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostTrdAnonSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal RoundLot;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoundLotSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PriceTypeEnum PxTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PxTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string SettlBizDays;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CheckMarketOrderEnum ChkMktOrd;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChkMktOrdSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class TickRules_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TickRuleScopes")]
        public TickRuleScopes_Block_t[] TickRuleScopes;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string TickRuleID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal StartTickPxRng;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal EndTickPxRng;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TickIncr;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class TickRuleScopes_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TrdTypeEnum TrdType;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProductComplexEnum TickRuleProdCmplx;
    }

    
    


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class QuoteSizeRules_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MinBidSz;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinBidSzSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MinOfrSz;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinOfrSzSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string FastMktInd;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class PxRngRules_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string PxRngRuleID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProductComplexEnum PxRngProdCmplx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PxRngProdCmplxSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal StartPxRng;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartPxRngSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal EndPxRng;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndPxRngSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PxRngValu;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PxRngValuSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PxRngPctg;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PxRngPctgSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class AuctTypRules_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AuctionTypeEnum AuctTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string ClsdBkInd;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string MktImbalInd;
    }

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class TrdgSesRules_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TradingSessionIdEnum SesID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TradingSessionSubIdEnum SesSub;
    }

    
    


    

    

    

    

    

    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class MarketSegmentGrp_Block_t
    {

        /// <remarks/>
        public SecurityTradingRules_Block_t SecTrdgRules;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MktSegID;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrmtLegGrp_Block_t))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class InstrumentLeg_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sym;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LegSecurityIDSourceEnum Src;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LegSecurityTypeEnum SecTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LegSideEnum Side;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal RatioQty;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RatioQtySpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Px;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PxSpecified;
    }


    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class InstrmtLegGrp_Block_t : InstrumentLeg_Block_t
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class UnderlyingInstrument_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MktSegID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnderlyingInstrumentSecurityIDSourceEnum Src;
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class InstrAttrib_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public InstrAttribTypeEnum Typ;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Val;
    }

    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class Instrument_Extension_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrAttrib")]
        public InstrAttrib_Block_t[] InstrAttrib;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class EvntGrp_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EventTypeEnum EventTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime Dt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DtSpecified;
    }

    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class Volatility_Corridor_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string VolCorOpnAuct;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string VolCorIntrAuct;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string VolCorClsAuct;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string VolCorCont;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class InstrumentParty_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public InstrumentPartyIDSourceEnum Src;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int R;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Qual;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QualSpecified;
    }

    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class SecAltIDGrp_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AltID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SecurityAltIDSourceEnum AltIDSrc;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AltIDSrcSpecified;
    }


    





    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class Instrument_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AID")]
        public SecAltIDGrp_Block_t[] AID;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pty")]
        public InstrumentParty_Block_t[] Pty;

        /// <remarks/>
        public Volatility_Corridor_Block_t VolCor;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Evnt")]
        public EvntGrp_Block_t[] Evnt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SecurityIDSourceEnum Src;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CFI;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SecurityTypeEnum SecTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Exch;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProductComplexEnum ProdCmplx;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime MatDt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MatDtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MMY;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ContractCycleTypeEnum CntrctCycTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CntrctCycTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ContractCycleSubTypeEnum CntrctCycSubTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CntrctCycSubTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime CntrctDt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CntrctDtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CntrctMY;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal StrkPx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StrkPxSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string StrkPxPrcsn;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string PxPrcsn;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal OrigStrkPx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrigStrkPxSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Mult;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MultSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PutOrCallEnum PutCall;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PutCallSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string OptAt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string CntrctGenNum;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ExerciseStyleEnum ExerStyle;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExerStyleSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MinPxIncr;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinPxIncrSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MinPxIncrClr;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinPxIncrClrSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MinPxIncrAmt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinPxIncrAmtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SecurityStatusEnum Status;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LowExerPxOptnInd;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValMeth;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SettlMeth;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string SettlSubMeth;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sym;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SettlCcy;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DepositTypeEnum DpstTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DpstTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string RefTickTblID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AssetTypeEnum AssetTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssetTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AssetSubTypeEnum AssetSubTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssetSubTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ULSym;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal CpnRt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CpnRtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime CpnPmt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CpnPmtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime PrevCpnPmt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrevCpnPmtSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccruedInterestCalculationMethodEnum CpnDayCnt;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CpnDayCntSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CouponTypeEnum CpnTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CpnTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Issr;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IssuCtry;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime Issued;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssuedSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal RoundLot;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoundLotSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MinTradeVol;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinTradeVolSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FlatIndicatorEnum FlatIndicator;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlatIndicatorSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WarrantTypeEnum WarrantTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarrantTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CoverIndicatorEnum CoverInd;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoverIndSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string QuotStartTm;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string QuotEndTm;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public InstrumentAuctionTypeEnum InstrmtAuctTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstrmtAuctTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string RatioMult;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ContractIdentificationEligibilityEnum CntrctIDElig;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CntrctIDEligSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public IsPrimaryFlagEnum Pri;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ContractFrequencyEnum CntrctFreq;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CntrctFreqSpecified;
    }










    

    

    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class MarketDataFeedTypes_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MDFeedTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MDBookTypeEnum MDBkTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string MktDepth;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string MktDepthTmIntvl;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string MDRcvryTmIntvl;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SvcLctnID1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SvcLctnSubID1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SvcLctnID2;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SvcLctnSubID2;
    }

    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class FlexProdEligs_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProductComplexEnum FlexProdEligCmplx;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlexProdElig;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class MatchRules_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProductComplexEnum MtchRuleProdCmplx;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MtchAlgo;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MatchTypeEnum MtchTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MtchTypSpecified;
    }

    




    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class InstrmtScope_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public InstrumentScopeOperatorEnum Oper;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SecurityTypeEnum SecTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SecSubTyp;
    }

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class RelatedMktSeg_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MarketSegmentRelationshipEnum Rltnshp;
    }

    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class Underlying_Block_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Exch;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sym;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnderlyingSecurityIDSourceEnum Src;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SrcSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PrevClsPx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrevClsPxSpecified;
    }

    

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityDefinitionUpdateReport_message_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityStatus_message_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityDefinition_message_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MarketDefinition_message_t))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class Abstract_message_t
    {

        /// <remarks/>
        public MessageHeader_t Hdr;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    public partial class MessageHeader_t : BaseHeader_t
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    [System.Xml.Serialization.XmlRootAttribute("MktDef", Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", IsNullable = false)]
    public partial class MarketDefinition_message_t : Abstract_message_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Undly")]
        public Underlying_Block_t Undly;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RelatedMktSeg")]
        public RelatedMktSeg_Block_t[] RelatedMktSeg;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrmtScope")]
        public InstrmtScope_Block_t[] InstrmtScope;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MtchRules")]
        public MatchRules_Block_t[] MtchRules;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FlexProdEligs")]
        public FlexProdEligs_Block_t[] FlexProdEligs;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BaseTrdgRules")]
        public BaseTrdgRules_Block_t BaseTrdgRules;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MDFeedTyps")]
        public MarketDataFeedTypes_Block_t[] MDFeedTyps;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MktID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MktSegID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MktSeg;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MarketSegmentDesc;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sym;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParentMktSegmID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MarketSegmentStatusEnum MktSegStat;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MktSegStatSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public USApprovalEnum USApprvl;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USApprvlSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string PartID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string NegDur;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string MaxOfstRFQExpireTm;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string OfstSTPEfctvTm;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime EfctvBizDt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime NxtEfctvBizDt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MarketSegmentTypeEnum MktSegTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MktSegTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MarketSegmentSubTypeEnum MktSegSubTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MktSegSubTypSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DecaySplitEnum DecaySplit;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DecaySplitSpecified;
    }


    

    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    [System.Xml.Serialization.XmlRootAttribute("SecDef", Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", IsNullable = false)]
    public partial class SecurityDefinition_message_t : Abstract_message_t
    {

        /// <remarks/>
        public Instrument_Block_t Instrmt;

        /// <remarks/>
        public Instrument_Extension_Block_t InstrmtExt;

        /// <remarks/>
        public UnderlyingInstrument_Block_t Undly;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Leg")]
        public InstrmtLegGrp_Block_t[] Leg;

        /// <remarks/>
        public MarketSegmentGrp_Block_t MktSegGrp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime TxnTm;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TxnTmSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PriSetPx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriSetPxSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ContractDisplayInstructionEnum CntrctDispInstr;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CntrctDispInstrSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string DispDay;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string DispReltvDay;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string DispWk;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string DispM;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string DispQ;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DisplaySeasonEnum DispS;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DispSSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string DispY;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DispName;
    }

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    [System.Xml.Serialization.XmlRootAttribute("SecStat", Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", IsNullable = false)]
    public partial class SecurityStatus_message_t : Abstract_message_t
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClrPxPrm")]
        public ClearingPriceParameters_Block_t[] ClrPxPrm;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MktSegID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SecurityIDSourceEnum Src;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SecurityTypeEnum SecTyp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PriSetPx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriSetPxSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SetPx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SetPxSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2")]
    [System.Xml.Serialization.XmlRootAttribute("SecDefUpd", Namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", IsNullable = false)]
    public partial class SecurityDefinitionUpdateReport_message_t : Abstract_message_t
    {

        /// <remarks/>
        public Instrument_Block_t Instrmt;

        /// <remarks/>
        public Instrument_Extension_Block_t InstrmtExt;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Leg")]
        public InstrmtLegGrp_Block_t[] Leg;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MktSegGrp")]
        public MarketSegmentGrp_Block_t[] MktSegGrp;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SecurityUpdateActionEnum UpdActn;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdActnSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime TxnTm;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TxnTmSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PriSetPx;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriSetPxSpecified;
    }

    
}