//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FlyDocLibrary.SubmissionService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SubmissionServiceSoap", Namespace="urn:SubmissionService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(string[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(int[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(double[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Var[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSFile[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubNode[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Transport[]))]
    public partial class SubmissionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SessionHeader sessionHeaderValueField;
        
        private System.Threading.SendOrPostCallback SubmitOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitTransportOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitXMLOperationCompleted;
        
        private ExtractionHeader extractionHeaderValueField;
        
        private System.Threading.SendOrPostCallback ExtractFirstOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExtractNextOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileAppendOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListResourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveResourceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SubmissionService() {
            this.Url = global::FlyDocLibrary.Properties.Settings.Default.FlyDoc_FlyDocLibrary_SubmissionService_SubmissionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SessionHeader SessionHeaderValue {
            get {
                return this.sessionHeaderValueField;
            }
            set {
                this.sessionHeaderValueField = value;
            }
        }
        
        public ExtractionHeader ExtractionHeaderValue {
            get {
                return this.extractionHeaderValueField;
            }
            set {
                this.extractionHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubmitCompletedEventHandler SubmitCompleted;
        
        /// <remarks/>
        public event SubmitTransportCompletedEventHandler SubmitTransportCompleted;
        
        /// <remarks/>
        public event SubmitXMLCompletedEventHandler SubmitXMLCompleted;
        
        /// <remarks/>
        public event ExtractFirstCompletedEventHandler ExtractFirstCompleted;
        
        /// <remarks/>
        public event ExtractNextCompletedEventHandler ExtractNextCompleted;
        
        /// <remarks/>
        public event ConvertFileCompletedEventHandler ConvertFileCompleted;
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        public event UploadFileAppendCompletedEventHandler UploadFileAppendCompleted;
        
        /// <remarks/>
        public event DownloadFileCompletedEventHandler DownloadFileCompleted;
        
        /// <remarks/>
        public event RegisterResourceCompletedEventHandler RegisterResourceCompleted;
        
        /// <remarks/>
        public event ListResourcesCompletedEventHandler ListResourcesCompleted;
        
        /// <remarks/>
        public event DeleteResourceCompletedEventHandler DeleteResourceCompleted;
        
        /// <remarks/>
        public event RetrieveResourceCompletedEventHandler RetrieveResourceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#Submit", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SubmissionResult Submit(string subject, BusinessData document, BusinessRules rules) {
            object[] results = this.Invoke("Submit", new object[] {
                        subject,
                        document,
                        rules});
            return ((SubmissionResult)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitAsync(string subject, BusinessData document, BusinessRules rules) {
            this.SubmitAsync(subject, document, rules, null);
        }
        
        /// <remarks/>
        public void SubmitAsync(string subject, BusinessData document, BusinessRules rules, object userState) {
            if ((this.SubmitOperationCompleted == null)) {
                this.SubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitOperationCompleted);
            }
            this.InvokeAsync("Submit", new object[] {
                        subject,
                        document,
                        rules}, this.SubmitOperationCompleted, userState);
        }
        
        private void OnSubmitOperationCompleted(object arg) {
            if ((this.SubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitCompleted(this, new SubmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#SubmitTransport", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SubmissionResult SubmitTransport(Transport transport) {
            object[] results = this.Invoke("SubmitTransport", new object[] {
                        transport});
            return ((SubmissionResult)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitTransportAsync(Transport transport) {
            this.SubmitTransportAsync(transport, null);
        }
        
        /// <remarks/>
        public void SubmitTransportAsync(Transport transport, object userState) {
            if ((this.SubmitTransportOperationCompleted == null)) {
                this.SubmitTransportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitTransportOperationCompleted);
            }
            this.InvokeAsync("SubmitTransport", new object[] {
                        transport}, this.SubmitTransportOperationCompleted, userState);
        }
        
        private void OnSubmitTransportOperationCompleted(object arg) {
            if ((this.SubmitTransportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitTransportCompleted(this, new SubmitTransportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#SubmitXML", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SubmissionResults SubmitXML(XMLDescription xml) {
            object[] results = this.Invoke("SubmitXML", new object[] {
                        xml});
            return ((SubmissionResults)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitXMLAsync(XMLDescription xml) {
            this.SubmitXMLAsync(xml, null);
        }
        
        /// <remarks/>
        public void SubmitXMLAsync(XMLDescription xml, object userState) {
            if ((this.SubmitXMLOperationCompleted == null)) {
                this.SubmitXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitXMLOperationCompleted);
            }
            this.InvokeAsync("SubmitXML", new object[] {
                        xml}, this.SubmitXMLOperationCompleted, userState);
        }
        
        private void OnSubmitXMLOperationCompleted(object arg) {
            if ((this.SubmitXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitXMLCompleted(this, new SubmitXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ExtractionHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#ExtractFirst", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public ExtractionResult ExtractFirst(BusinessData document, BusinessRules rules, ExtractionParameters @params) {
            object[] results = this.Invoke("ExtractFirst", new object[] {
                        document,
                        rules,
                        @params});
            return ((ExtractionResult)(results[0]));
        }
        
        /// <remarks/>
        public void ExtractFirstAsync(BusinessData document, BusinessRules rules, ExtractionParameters @params) {
            this.ExtractFirstAsync(document, rules, @params, null);
        }
        
        /// <remarks/>
        public void ExtractFirstAsync(BusinessData document, BusinessRules rules, ExtractionParameters @params, object userState) {
            if ((this.ExtractFirstOperationCompleted == null)) {
                this.ExtractFirstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtractFirstOperationCompleted);
            }
            this.InvokeAsync("ExtractFirst", new object[] {
                        document,
                        rules,
                        @params}, this.ExtractFirstOperationCompleted, userState);
        }
        
        private void OnExtractFirstOperationCompleted(object arg) {
            if ((this.ExtractFirstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtractFirstCompleted(this, new ExtractFirstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ExtractionHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#ExtractNext", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public ExtractionResult ExtractNext(ExtractionParameters @params) {
            object[] results = this.Invoke("ExtractNext", new object[] {
                        @params});
            return ((ExtractionResult)(results[0]));
        }
        
        /// <remarks/>
        public void ExtractNextAsync(ExtractionParameters @params) {
            this.ExtractNextAsync(@params, null);
        }
        
        /// <remarks/>
        public void ExtractNextAsync(ExtractionParameters @params, object userState) {
            if ((this.ExtractNextOperationCompleted == null)) {
                this.ExtractNextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtractNextOperationCompleted);
            }
            this.InvokeAsync("ExtractNext", new object[] {
                        @params}, this.ExtractNextOperationCompleted, userState);
        }
        
        private void OnExtractNextOperationCompleted(object arg) {
            if ((this.ExtractNextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtractNextCompleted(this, new ExtractNextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#ConvertFile", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public ConversionResult ConvertFile(WSFile inputFile, ConversionParameters @params) {
            object[] results = this.Invoke("ConvertFile", new object[] {
                        inputFile,
                        @params});
            return ((ConversionResult)(results[0]));
        }
        
        /// <remarks/>
        public void ConvertFileAsync(WSFile inputFile, ConversionParameters @params) {
            this.ConvertFileAsync(inputFile, @params, null);
        }
        
        /// <remarks/>
        public void ConvertFileAsync(WSFile inputFile, ConversionParameters @params, object userState) {
            if ((this.ConvertFileOperationCompleted == null)) {
                this.ConvertFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertFileOperationCompleted);
            }
            this.InvokeAsync("ConvertFile", new object[] {
                        inputFile,
                        @params}, this.ConvertFileOperationCompleted, userState);
        }
        
        private void OnConvertFileOperationCompleted(object arg) {
            if ((this.ConvertFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertFileCompleted(this, new ConvertFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#UploadFile", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public WSFile UploadFile([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] fileContent, string name) {
            object[] results = this.Invoke("UploadFile", new object[] {
                        fileContent,
                        name});
            return ((WSFile)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileAsync(byte[] fileContent, string name) {
            this.UploadFileAsync(fileContent, name, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(byte[] fileContent, string name, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        fileContent,
                        name}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#UploadFileAppend", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public WSFile UploadFileAppend([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] fileContent, WSFile destWSFile) {
            object[] results = this.Invoke("UploadFileAppend", new object[] {
                        fileContent,
                        destWSFile});
            return ((WSFile)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileAppendAsync(byte[] fileContent, WSFile destWSFile) {
            this.UploadFileAppendAsync(fileContent, destWSFile, null);
        }
        
        /// <remarks/>
        public void UploadFileAppendAsync(byte[] fileContent, WSFile destWSFile, object userState) {
            if ((this.UploadFileAppendOperationCompleted == null)) {
                this.UploadFileAppendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileAppendOperationCompleted);
            }
            this.InvokeAsync("UploadFileAppend", new object[] {
                        fileContent,
                        destWSFile}, this.UploadFileAppendOperationCompleted, userState);
        }
        
        private void OnUploadFileAppendOperationCompleted(object arg) {
            if ((this.UploadFileAppendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileAppendCompleted(this, new UploadFileAppendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#DownloadFile", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="base64Binary")]
        public byte[] DownloadFile(WSFile wsFile) {
            object[] results = this.Invoke("DownloadFile", new object[] {
                        wsFile});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DownloadFileAsync(WSFile wsFile) {
            this.DownloadFileAsync(wsFile, null);
        }
        
        /// <remarks/>
        public void DownloadFileAsync(WSFile wsFile, object userState) {
            if ((this.DownloadFileOperationCompleted == null)) {
                this.DownloadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadFileOperationCompleted);
            }
            this.InvokeAsync("DownloadFile", new object[] {
                        wsFile}, this.DownloadFileOperationCompleted, userState);
        }
        
        private void OnDownloadFileOperationCompleted(object arg) {
            if ((this.DownloadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadFileCompleted(this, new DownloadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#RegisterResource", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegisterResource(WSFile resource, RESOURCE_TYPE type, bool published, bool overwritePrevious) {
            this.Invoke("RegisterResource", new object[] {
                        resource,
                        type,
                        published,
                        overwritePrevious});
        }
        
        /// <remarks/>
        public void RegisterResourceAsync(WSFile resource, RESOURCE_TYPE type, bool published, bool overwritePrevious) {
            this.RegisterResourceAsync(resource, type, published, overwritePrevious, null);
        }
        
        /// <remarks/>
        public void RegisterResourceAsync(WSFile resource, RESOURCE_TYPE type, bool published, bool overwritePrevious, object userState) {
            if ((this.RegisterResourceOperationCompleted == null)) {
                this.RegisterResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterResourceOperationCompleted);
            }
            this.InvokeAsync("RegisterResource", new object[] {
                        resource,
                        type,
                        published,
                        overwritePrevious}, this.RegisterResourceOperationCompleted, userState);
        }
        
        private void OnRegisterResourceOperationCompleted(object arg) {
            if ((this.RegisterResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterResourceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#ListResources", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public Resources ListResources(RESOURCE_TYPE type, bool published) {
            object[] results = this.Invoke("ListResources", new object[] {
                        type,
                        published});
            return ((Resources)(results[0]));
        }
        
        /// <remarks/>
        public void ListResourcesAsync(RESOURCE_TYPE type, bool published) {
            this.ListResourcesAsync(type, published, null);
        }
        
        /// <remarks/>
        public void ListResourcesAsync(RESOURCE_TYPE type, bool published, object userState) {
            if ((this.ListResourcesOperationCompleted == null)) {
                this.ListResourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListResourcesOperationCompleted);
            }
            this.InvokeAsync("ListResources", new object[] {
                        type,
                        published}, this.ListResourcesOperationCompleted, userState);
        }
        
        private void OnListResourcesOperationCompleted(object arg) {
            if ((this.ListResourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListResourcesCompleted(this, new ListResourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#DeleteResource", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteResource(string resourceName, RESOURCE_TYPE type, bool published) {
            this.Invoke("DeleteResource", new object[] {
                        resourceName,
                        type,
                        published});
        }
        
        /// <remarks/>
        public void DeleteResourceAsync(string resourceName, RESOURCE_TYPE type, bool published) {
            this.DeleteResourceAsync(resourceName, type, published, null);
        }
        
        /// <remarks/>
        public void DeleteResourceAsync(string resourceName, RESOURCE_TYPE type, bool published, object userState) {
            if ((this.DeleteResourceOperationCompleted == null)) {
                this.DeleteResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteResourceOperationCompleted);
            }
            this.InvokeAsync("DeleteResource", new object[] {
                        resourceName,
                        type,
                        published}, this.DeleteResourceOperationCompleted, userState);
        }
        
        private void OnDeleteResourceOperationCompleted(object arg) {
            if ((this.DeleteResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteResourceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#RetrieveResource", RequestNamespace="urn:SubmissionService", ResponseNamespace="urn:SubmissionService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public WSFile RetrieveResource(string resourceName, RESOURCE_TYPE type, bool published, WSFILE_MODE eMode) {
            object[] results = this.Invoke("RetrieveResource", new object[] {
                        resourceName,
                        type,
                        published,
                        eMode});
            return ((WSFile)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveResourceAsync(string resourceName, RESOURCE_TYPE type, bool published, WSFILE_MODE eMode) {
            this.RetrieveResourceAsync(resourceName, type, published, eMode, null);
        }
        
        /// <remarks/>
        public void RetrieveResourceAsync(string resourceName, RESOURCE_TYPE type, bool published, WSFILE_MODE eMode, object userState) {
            if ((this.RetrieveResourceOperationCompleted == null)) {
                this.RetrieveResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveResourceOperationCompleted);
            }
            this.InvokeAsync("RetrieveResource", new object[] {
                        resourceName,
                        type,
                        published,
                        eMode}, this.RetrieveResourceOperationCompleted, userState);
        }
        
        private void OnRetrieveResourceOperationCompleted(object arg) {
            if ((this.RetrieveResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveResourceCompleted(this, new RetrieveResourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    [System.Xml.Serialization.XmlRootAttribute("SessionHeaderValue", Namespace="urn:SubmissionService", IsNullable=false)]
    public partial class SessionHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string sessionIDField;
        
        /// <remarks/>
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class Resources {
        
        private int nResourcesField;
        
        private string[] resourcesField;
        
        /// <remarks/>
        public int nResources {
            get {
                return this.nResourcesField;
            }
            set {
                this.nResourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class ConversionResult {
        
        private WSFile convertedFileField;
        
        /// <remarks/>
        public WSFile convertedFile {
            get {
                return this.convertedFileField;
            }
            set {
                this.convertedFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class WSFile {
        
        private string nameField;
        
        private WSFILE_MODE modeField;
        
        private byte[] contentField;
        
        private string urlField;
        
        private string storageIDField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public WSFILE_MODE mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string storageID {
            get {
                return this.storageIDField;
            }
            set {
                this.storageIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public enum WSFILE_MODE {
        
        /// <remarks/>
        MODE_UNDEFINED,
        
        /// <remarks/>
        MODE_ON_SERVER,
        
        /// <remarks/>
        MODE_INLINED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class ConversionParameters {
        
        private string inputTypeField;
        
        private string outputTypeField;
        
        private string customParametersField;
        
        private WSFILE_MODE outputFileModeField;
        
        /// <remarks/>
        public string inputType {
            get {
                return this.inputTypeField;
            }
            set {
                this.inputTypeField = value;
            }
        }
        
        /// <remarks/>
        public string outputType {
            get {
                return this.outputTypeField;
            }
            set {
                this.outputTypeField = value;
            }
        }
        
        /// <remarks/>
        public string customParameters {
            get {
                return this.customParametersField;
            }
            set {
                this.customParametersField = value;
            }
        }
        
        /// <remarks/>
        public WSFILE_MODE outputFileMode {
            get {
                return this.outputFileModeField;
            }
            set {
                this.outputFileModeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class ExtractionResult {
        
        private bool noMoreItemsField;
        
        private int nTransportsField;
        
        private Transport[] transportsField;
        
        /// <remarks/>
        public bool noMoreItems {
            get {
                return this.noMoreItemsField;
            }
            set {
                this.noMoreItemsField = value;
            }
        }
        
        /// <remarks/>
        public int nTransports {
            get {
                return this.nTransportsField;
            }
            set {
                this.nTransportsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Transport[] transports {
            get {
                return this.transportsField;
            }
            set {
                this.transportsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class Transport {
        
        private string transportNameField;
        
        private string recipientTypeField;
        
        private string transportIndexField;
        
        private int nVarsField;
        
        private Var[] varsField;
        
        private int nSubnodesField;
        
        private SubNode[] subnodesField;
        
        private int nAttachmentsField;
        
        private Attachment[] attachmentsField;
        
        /// <remarks/>
        public string transportName {
            get {
                return this.transportNameField;
            }
            set {
                this.transportNameField = value;
            }
        }
        
        /// <remarks/>
        public string recipientType {
            get {
                return this.recipientTypeField;
            }
            set {
                this.recipientTypeField = value;
            }
        }
        
        /// <remarks/>
        public string transportIndex {
            get {
                return this.transportIndexField;
            }
            set {
                this.transportIndexField = value;
            }
        }
        
        /// <remarks/>
        public int nVars {
            get {
                return this.nVarsField;
            }
            set {
                this.nVarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Var[] vars {
            get {
                return this.varsField;
            }
            set {
                this.varsField = value;
            }
        }
        
        /// <remarks/>
        public int nSubnodes {
            get {
                return this.nSubnodesField;
            }
            set {
                this.nSubnodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SubNode[] subnodes {
            get {
                return this.subnodesField;
            }
            set {
                this.subnodesField = value;
            }
        }
        
        /// <remarks/>
        public int nAttachments {
            get {
                return this.nAttachmentsField;
            }
            set {
                this.nAttachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class Var {
        
        private string attributeField;
        
        private VAR_TYPE typeField;
        
        private string simpleValueField;
        
        private int nValuesField;
        
        private string[] multipleStringValuesField;
        
        private int[] multipleLongValuesField;
        
        private double[] multipleDoubleValuesField;
        
        /// <remarks/>
        public string attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        public VAR_TYPE type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string simpleValue {
            get {
                return this.simpleValueField;
            }
            set {
                this.simpleValueField = value;
            }
        }
        
        /// <remarks/>
        public int nValues {
            get {
                return this.nValuesField;
            }
            set {
                this.nValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] multipleStringValues {
            get {
                return this.multipleStringValuesField;
            }
            set {
                this.multipleStringValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public int[] multipleLongValues {
            get {
                return this.multipleLongValuesField;
            }
            set {
                this.multipleLongValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public double[] multipleDoubleValues {
            get {
                return this.multipleDoubleValuesField;
            }
            set {
                this.multipleDoubleValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public enum VAR_TYPE {
        
        /// <remarks/>
        TYPE_STRING,
        
        /// <remarks/>
        TYPE_DATETIME,
        
        /// <remarks/>
        TYPE_DOUBLE,
        
        /// <remarks/>
        TYPE_INTEGER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class SubNode {
        
        private string nameField;
        
        private string relativeNameField;
        
        private int nSubnodesField;
        
        private string[] subNodesField;
        
        private int nVarsField;
        
        private Var[] varsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string relativeName {
            get {
                return this.relativeNameField;
            }
            set {
                this.relativeNameField = value;
            }
        }
        
        /// <remarks/>
        public int nSubnodes {
            get {
                return this.nSubnodesField;
            }
            set {
                this.nSubnodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] subNodes {
            get {
                return this.subNodesField;
            }
            set {
                this.subNodesField = value;
            }
        }
        
        /// <remarks/>
        public int nVars {
            get {
                return this.nVarsField;
            }
            set {
                this.nVarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Var[] vars {
            get {
                return this.varsField;
            }
            set {
                this.varsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class Attachment {
        
        private string inputFormatField;
        
        private string outputFormatField;
        
        private string stylesheetField;
        
        private string outputNameField;
        
        private WSFile sourceAttachmentField;
        
        private int nConvertedAttachmentsField;
        
        private WSFile[] convertedAttachmentsField;
        
        /// <remarks/>
        public string inputFormat {
            get {
                return this.inputFormatField;
            }
            set {
                this.inputFormatField = value;
            }
        }
        
        /// <remarks/>
        public string outputFormat {
            get {
                return this.outputFormatField;
            }
            set {
                this.outputFormatField = value;
            }
        }
        
        /// <remarks/>
        public string stylesheet {
            get {
                return this.stylesheetField;
            }
            set {
                this.stylesheetField = value;
            }
        }
        
        /// <remarks/>
        public string outputName {
            get {
                return this.outputNameField;
            }
            set {
                this.outputNameField = value;
            }
        }
        
        /// <remarks/>
        public WSFile sourceAttachment {
            get {
                return this.sourceAttachmentField;
            }
            set {
                this.sourceAttachmentField = value;
            }
        }
        
        /// <remarks/>
        public int nConvertedAttachments {
            get {
                return this.nConvertedAttachmentsField;
            }
            set {
                this.nConvertedAttachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSFile[] convertedAttachments {
            get {
                return this.convertedAttachmentsField;
            }
            set {
                this.convertedAttachmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class ExtractionParameters {
        
        private int nItemsField;
        
        private bool fullPreviewModeField;
        
        private ATTACHMENTS_FILTER attachmentFilterField;
        
        private WSFILE_MODE outputFileModeField;
        
        private bool includeSubNodesField;
        
        private string startIndexField;
        
        /// <remarks/>
        public int nItems {
            get {
                return this.nItemsField;
            }
            set {
                this.nItemsField = value;
            }
        }
        
        /// <remarks/>
        public bool fullPreviewMode {
            get {
                return this.fullPreviewModeField;
            }
            set {
                this.fullPreviewModeField = value;
            }
        }
        
        /// <remarks/>
        public ATTACHMENTS_FILTER attachmentFilter {
            get {
                return this.attachmentFilterField;
            }
            set {
                this.attachmentFilterField = value;
            }
        }
        
        /// <remarks/>
        public WSFILE_MODE outputFileMode {
            get {
                return this.outputFileModeField;
            }
            set {
                this.outputFileModeField = value;
            }
        }
        
        /// <remarks/>
        public bool includeSubNodes {
            get {
                return this.includeSubNodesField;
            }
            set {
                this.includeSubNodesField = value;
            }
        }
        
        /// <remarks/>
        public string startIndex {
            get {
                return this.startIndexField;
            }
            set {
                this.startIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public enum ATTACHMENTS_FILTER {
        
        /// <remarks/>
        FILTER_NONE,
        
        /// <remarks/>
        FILTER_ALL,
        
        /// <remarks/>
        FILTER_CONVERTED,
        
        /// <remarks/>
        FILTER_SOURCE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class SubmissionResults {
        
        private string submissionIDField;
        
        private int nTransportField;
        
        private int[] transportIDsField;
        
        /// <remarks/>
        public string submissionID {
            get {
                return this.submissionIDField;
            }
            set {
                this.submissionIDField = value;
            }
        }
        
        /// <remarks/>
        public int nTransport {
            get {
                return this.nTransportField;
            }
            set {
                this.nTransportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public int[] transportIDs {
            get {
                return this.transportIDsField;
            }
            set {
                this.transportIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class XMLDescription {
        
        private WSFile xmlFileField;
        
        private int nAttachmentsField;
        
        private Attachment[] attachmentsField;
        
        /// <remarks/>
        public WSFile xmlFile {
            get {
                return this.xmlFileField;
            }
            set {
                this.xmlFileField = value;
            }
        }
        
        /// <remarks/>
        public int nAttachments {
            get {
                return this.nAttachmentsField;
            }
            set {
                this.nAttachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class SubmissionResult {
        
        private string submissionIDField;
        
        private int transportIDField;
        
        /// <remarks/>
        public string submissionID {
            get {
                return this.submissionIDField;
            }
            set {
                this.submissionIDField = value;
            }
        }
        
        /// <remarks/>
        public int transportID {
            get {
                return this.transportIDField;
            }
            set {
                this.transportIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class BusinessRules {
        
        private string configurationNameField;
        
        private string ruleNameField;
        
        /// <remarks/>
        public string configurationName {
            get {
                return this.configurationNameField;
            }
            set {
                this.configurationNameField = value;
            }
        }
        
        /// <remarks/>
        public string ruleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public partial class BusinessData {
        
        private WSFile fileField;
        
        private int nExternalVarsField;
        
        private Var[] externalVarsField;
        
        private int nAttachmentsField;
        
        private Attachment[] attachmentsField;
        
        /// <remarks/>
        public WSFile file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public int nExternalVars {
            get {
                return this.nExternalVarsField;
            }
            set {
                this.nExternalVarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Var[] externalVars {
            get {
                return this.externalVarsField;
            }
            set {
                this.externalVarsField = value;
            }
        }
        
        /// <remarks/>
        public int nAttachments {
            get {
                return this.nAttachmentsField;
            }
            set {
                this.nAttachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    [System.Xml.Serialization.XmlRootAttribute("ExtractionHeaderValue", Namespace="urn:SubmissionService", IsNullable=false)]
    public partial class ExtractionHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string extractionJobIDField;
        
        private string extractionDocIDField;
        
        private int offsetField;
        
        private int transportIndexField;
        
        /// <remarks/>
        public string ExtractionJobID {
            get {
                return this.extractionJobIDField;
            }
            set {
                this.extractionJobIDField = value;
            }
        }
        
        /// <remarks/>
        public string ExtractionDocID {
            get {
                return this.extractionDocIDField;
            }
            set {
                this.extractionDocIDField = value;
            }
        }
        
        /// <remarks/>
        public int offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        public int transportIndex {
            get {
                return this.transportIndexField;
            }
            set {
                this.transportIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SubmissionService")]
    public enum RESOURCE_TYPE {
        
        /// <remarks/>
        TYPE_SALESFORCE_LEAD_EMAILBODY,
        
        /// <remarks/>
        TYPE_SALESFORCE_LEAD_FAXCOVER,
        
        /// <remarks/>
        TYPE_SALESFORCE_CONTACT_EMAILBODY,
        
        /// <remarks/>
        TYPE_SALESFORCE_CONTACT_FAXCOVER,
        
        /// <remarks/>
        TYPE_SALESFORCE_SETTINGS,
        
        /// <remarks/>
        TYPE_STYLESHEET,
        
        /// <remarks/>
        TYPE_IMAGE,
        
        /// <remarks/>
        TYPE_COVER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitCompletedEventHandler(object sender, SubmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubmissionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubmissionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitTransportCompletedEventHandler(object sender, SubmitTransportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitTransportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitTransportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubmissionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubmissionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitXMLCompletedEventHandler(object sender, SubmitXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubmissionResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubmissionResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ExtractFirstCompletedEventHandler(object sender, ExtractFirstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtractFirstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtractFirstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtractionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtractionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ExtractNextCompletedEventHandler(object sender, ExtractNextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtractNextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtractNextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtractionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtractionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConvertFileCompletedEventHandler(object sender, ConvertFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConversionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConversionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UploadFileCompletedEventHandler(object sender, UploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSFile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSFile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UploadFileAppendCompletedEventHandler(object sender, UploadFileAppendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileAppendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileAppendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSFile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSFile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DownloadFileCompletedEventHandler(object sender, DownloadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RegisterResourceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListResourcesCompletedEventHandler(object sender, ListResourcesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListResourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListResourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resources Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resources)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteResourceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RetrieveResourceCompletedEventHandler(object sender, RetrieveResourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveResourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveResourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSFile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSFile)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591