using System;
using System.IO;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
//
using System.Xml.Serialization;
//
using EFS.ACommon;

namespace EFS.Common.EfsSend
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Ce code a été généré par un outil.
    //     Version du runtime :2.0.50727.1433
    //
    //     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
    //     le code est régénéré.
    // </auto-generated>
    //------------------------------------------------------------------------------
       

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    //
    // It was modified manually
    //

    #region Enums 
    /// <remarks/>
    public enum EfsSendFormatEnum
    {
        /// <remarks/>
        Text,

        /// <remarks/>
        Html,
    }
    #endregion
    //
    #region class EfsSendSubject
    /// <remarks/>
    public class EfsSendSubject
    {
        #region Members 
        /// <remarks/>
        [XmlAttributeAttribute()]
        public string encoding;
        private string value;
        #endregion 
        #region Accessors 
        /// <remarks/>
        [XmlTextAttribute()]
        public string Value {
            get {
                return this.value;
            }
            set {
                this.value = value;
            }
        }
        #endregion
        //
        #region constructor
        public EfsSendSubject()
        {
            encoding = System.Text.Encoding.Default.ToString();
		}
		#endregion constructor
    }
    #endregion
    #region class EfsSendBody
    /// <remarks/>
    public class EfsSendBody
    {
        #region Members 
        /// <remarks/>
        [XmlAttributeAttribute()]
        public EfsSendFormatEnum format;
        /// <remarks/>
        [XmlAttributeAttribute()]
        public string encoding;
        private string value;
        #endregion
        #region Accessors 
        /// <remarks/>
        [XmlTextAttribute()]
        public string Value {
            get {
                return this.value;
            }
            set {
                this.value = value;
            }
        }
        #endregion
        //
        #region Constructor 
        public EfsSendBody()
        {
            format = EfsSendFormatEnum.Text;
            encoding = System.Text.Encoding.Default.ToString();
        }
        #endregion Constructor
    }
    #endregion 
    #region class EfsSendStream
    /// <remarks/>
    public class EfsSendStream
    {
        #region Members 
        /// <remarks/>
        [XmlAttributeAttribute()]
        public string contenttype;        
        private string value;
        #endregion
        #region Accessors  
        /// <remarks/>
        [XmlTextAttribute()]
        public string Value {
            get {
                return this.value;
            }
            set {
                this.value = (StrFunc.IsFilled(value)?value.Trim():string.Empty);
            }
        }
        #endregion
        //
        #region Constructor 
        public EfsSendStream()
        {
            if(StrFunc.IsEmpty(contenttype))
                contenttype = MediaTypeNames.Application.Octet;
        }
        #endregion Constructor
    }
    #endregion
}
