//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.9168
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par xsd, Version=2.0.50727.3038.
// 
namespace EFS.SpheresRiskPerformance.RiskMethods.Span2CoreAPI.v1_14 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("portfolioLinkReq", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class portfolioLinkRequestMessage : requestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("portfolios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolioLink[] portfolios;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class portfolioLink : entityBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("portfolioId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] portfolioId;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(analytic))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marginMatrix))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(margin))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transaction))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class entityBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime createTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createTimeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public entityStatus status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updateTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateTimeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum entityStatus {
        
        /// <remarks/>
        DELETED,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        INSERTED,
        
        /// <remarks/>
        UPDATED,
        
        /// <remarks/>
        SUCCESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class portfolioStatisticsStats {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string tradeCount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal marginMaintAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public currency ccy;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum currency {
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        CHP,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        COP,
        
        /// <remarks/>
        CNY,
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        HKD,
        
        /// <remarks/>
        HUF,
        
        /// <remarks/>
        IDR,
        
        /// <remarks/>
        ILS,
        
        /// <remarks/>
        INR,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        KRW,
        
        /// <remarks/>
        MXN,
        
        /// <remarks/>
        MYR,
        
        /// <remarks/>
        NZD,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        PHP,
        
        /// <remarks/>
        PLN,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        SGD,
        
        /// <remarks/>
        THB,
        
        /// <remarks/>
        TRY,
        
        /// <remarks/>
        TWD,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        ZAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class portfolioStatistics {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cycle cycle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolioEntities entities;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolioStatisticsStats stats;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class cycle {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime date;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public cycleCode code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum cycleCode {
        
        /// <remarks/>
        AFTER_ITD,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        SUPER_EARLY,
        
        /// <remarks/>
        CUR,
        
        /// <remarks/>
        EARLY,
        
        /// <remarks/>
        EOD,
        
        /// <remarks/>
        ITD,
        
        /// <remarks/>
        FINAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class portfolioEntities {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string clrOrgId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string clrMbrFirmId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string custAcctId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pbAcctId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public origin origin;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum origin {
        
        /// <remarks/>
        CUST,
        
        /// <remarks/>
        HOUS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class messagePayload {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("string", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public transactionEncoding name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nameSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public transactionEncoding encoding;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool encodingSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public transactionFormat format;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public transactionSubformat subformat;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subformatSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum transactionEncoding {
        
        /// <remarks/>
        STRING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum transactionFormat {
        
        /// <remarks/>
        FIXML,
        
        /// <remarks/>
        FPML,
        
        /// <remarks/>
        CSV,
        
        /// <remarks/>
        RISK_API_JSON,
        
        /// <remarks/>
        SPAN_XML,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum transactionSubformat {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        IRS_TRADE_REG,
        
        /// <remarks/>
        CORE_FX,
        
        /// <remarks/>
        CORE_CDS,
        
        /// <remarks/>
        CORE_IRS,
        
        /// <remarks/>
        FUT_COMP_DTL,
        
        /// <remarks/>
        FUT_COMP_PORT,
        
        /// <remarks/>
        FUT_COMP_SMRY,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(riskPayload))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class stringBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class riskPayload : stringBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public riskFramework riskFramework;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool riskFrameworkSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum riskFramework {
        
        /// <remarks/>
        CURRENT,
        
        /// <remarks/>
        NEXT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class scenarioPoint {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal amt;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class portfolioMarginAmounts {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal futCurrAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool futCurrAmtSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal futPreAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal futPostAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal otcCurrAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool otcCurrAmtSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal otcPreAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal otcPostAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal diffAmt;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class incrementalMarginAmounts {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal initBaseAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal initDiffAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maintBaseAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maintDiffAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal concBaseAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal concDiffAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal skewBaseAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skewBaseAmtSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal skewDiffAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skewDiffAmtSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal npvBaseAmt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal npvDiffAmt;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class marginAmounts {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("currencyAmounts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public marginAmounts[] currencyAmounts;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public incrementalMarginAmounts incremental;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolioMarginAmounts portfolio;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scPt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public scenarioPoint[] scPt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public currency ccy;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ccyRate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ccyRateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal @base;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal conc;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal concDelta;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool concDeltaSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal concGamma;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool concGammaSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal concSkew;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool concSkewSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal concVega;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool concVegaSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal init;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maint;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal npv;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool npvSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal nonOptVal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nonOptValSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal optVal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optValSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal skew;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skewSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class transactionPayload {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("string", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public transactionEncoding encoding;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool encodingSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public transactionFormat format;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public transactionSubformat subformat;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subformatSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class error {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string msg;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reportBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(syncReportBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marginMatrixReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transactionReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioStatisticsReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(asyncReportBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(payloadReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(analyticReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marginReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optimizerReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(requestBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(payloadRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(analyticRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marginRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transactionRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioStatisticsRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioLinkRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optimizerRequestMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class messageBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(syncReportBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marginMatrixReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transactionReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioStatisticsReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(asyncReportBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(payloadReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(analyticReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marginReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optimizerReportMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class reportBase : messageBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public error error;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marginMatrixReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transactionReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioStatisticsReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioReportMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class syncReportBase : reportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public syncReportStatus status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum syncReportStatus {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        SUCCESS_WITH_ERRORS,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(payloadReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(analyticReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marginReportMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optimizerReportMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class asyncReportBase : reportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public asyncReportStatus status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum asyncReportStatus {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        PROCESSING,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        SUCCESS_WITH_ERRORS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class payloadReportMessage : asyncReportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payload", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public messagePayload[] payload;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(payloadRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(analyticRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marginRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transactionRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioStatisticsRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(portfolioLinkRequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optimizerRequestMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class requestBase : messageBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reqUserId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class payloadRequestMessage : requestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public messagePayload payload;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class transaction : entityBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public error error;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public transactionPayload payload;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string portfolioId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public transactionType type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum transactionType {
        
        /// <remarks/>
        DELTA_LADDER,
        
        /// <remarks/>
        TRADE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class analytic : entityBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string portfolioId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public analyticType type;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum analyticType {
        
        /// <remarks/>
        PMOPT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class marginMatrix : entityBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public transactionPayload payload;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class margin : entityBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public transaction[] transactions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public marginAmounts amounts;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payload", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public riskPayload[] payload;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime asOfTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool asOfTimeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string portfolioId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public riskFramework riskFramework;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool riskFrameworkSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public settlementQualifier settleQual;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool settleQualSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public settlementIndicator settleInd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool settleIndSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum settlementQualifier {
        
        /// <remarks/>
        COMP,
        
        /// <remarks/>
        EARLY,
        
        /// <remarks/>
        FINAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum settlementIndicator {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public partial class portfolio : entityBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolioEntities entities;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public transaction[] transactions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string desc;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public currency rptCcy;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rptCcySpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("portfolioReq", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class portfolioRequestMessage : requestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolio portfolio;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("portfolioRpt", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class portfolioReportMessage : syncReportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("portfolio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolio[] portfolio;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("portfolioStatsReq", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class portfolioStatisticsRequestMessage : requestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cycle cycle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entities", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolioEntities[] entities;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("portfolioStatsRpt", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class portfolioStatisticsReportMessage : syncReportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("portfolioStats", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public portfolioStatistics[] portfolioStats;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("transactionReq", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class transactionRequestMessage : requestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public transaction[] transaction;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public processingMode processingMode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool processingModeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    public enum processingMode {
        
        /// <remarks/>
        COMPLETE,
        
        /// <remarks/>
        PARTIAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("transactionRpt", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class transactionReportMessage : syncReportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public transaction[] transaction;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("marginReq", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class marginRequestMessage : requestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cycle cycle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public margin margin;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("marginRpt", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class marginReportMessage : asyncReportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cycle cycle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("margin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public margin[] margin;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("marginMatrixRpt", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class marginMatrixReportMessage : syncReportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("marginMatrix", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public marginMatrix[] marginMatrix;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("analyticReq", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class analyticRequestMessage : requestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public analytic analytic;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("analyticRpt", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class analyticReportMessage : asyncReportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public analytic analytic;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("optimizerReq", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class optimizerRequestMessage : requestBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public margin margin;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmegroup.com/schema/core/1.14")]
    [System.Xml.Serialization.XmlRootAttribute("optimizerRpt", Namespace="http://cmegroup.com/schema/core/1.14", IsNullable=false)]
    public partial class optimizerReportMessage : asyncReportBase {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("margin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public margin[] margin;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public transaction[] transaction;
    }
}
