<?xml version="1.0" encoding="utf-8"?>
<Database Name="RD_SPHERES_TST260" Class="MARGINDETTRACKDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SVR-MSS-2\SVRMSS2;Initial Catalog=RD_SPHERES_TST260;Persist Security Info=True;User ID=sa" SettingsObjectName="EFS.SpheresRiskPerformance.Properties.Settings" SettingsPropertyName="RD_SPHERES_TST260ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MARGINDETTRACK" Member="MARGINDETTRACK">
    <Type Name="MARGINDETTRACK">
      <Column Name="IDMARGINTRACK" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="IDT" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="MARGINXML" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>