<?xml version="1.0" encoding="utf-8"?>
<!-- RD 20170228 mise à jour de la table -->
<Database Name="SPHERES_MARKETDATA" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SVR-MSS-2\SVRMSS2;Initial Catalog=SPHERES_MARKETDATA;Persist Security Info=True;User ID=sa" SettingsObjectName="EFS.SpheresIO.Properties.Settings" SettingsPropertyName="SPHERES_MARKETDATAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IOTRACKCOMPARE" Member="IOTRACKCOMPARE">
    <Type Name="IOTRACKCOMPARE">
      <Column Name="IDIOTRACK" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="MESSAGE" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="MATCHSTATUS" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="INTDATAID" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="INTDATAIDS" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="EXTDATAID" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="INTVALUE1" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="INTVALUE2" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="EXTVALUE1" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="EXTVALUE2" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="MATCHVALUE1" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="MATCHVALUE2" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="DTINS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDAINS" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="UNITVALUE1" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="ROWVERSION" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="UNITVALUE2" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
</Database>