#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFS.SpheresIO.SpheresObjets
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SPHERES_MARKETDATA")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::EFS.SpheresIO.Properties.Settings.Default.SPHERES_MARKETDATAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IOTRACKCOMPARE> IOTRACKCOMPARE
		{
			get
			{
				return this.GetTable<IOTRACKCOMPARE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IOTRACKCOMPARE")]
	public partial class IOTRACKCOMPARE
	{
		
		private decimal _IDIOTRACK;
		
		private string _MESSAGE;
		
		private string _MATCHSTATUS;
		
		private System.Nullable<decimal> _INTDATAID;
		
		private string _INTDATAIDS;
		
		private System.Nullable<decimal> _EXTDATAID;
		
		private System.Nullable<decimal> _INTVALUE1;
		
		private System.Nullable<decimal> _INTVALUE2;
		
		private System.Nullable<decimal> _EXTVALUE1;
		
		private System.Nullable<decimal> _EXTVALUE2;
		
		private System.Nullable<decimal> _MATCHVALUE1;
		
		private System.Nullable<decimal> _MATCHVALUE2;
		
		private System.DateTime _DTINS;
		
		private decimal _IDAINS;
		
		private string _UNITVALUE1;
		
		private System.Data.Linq.Binary _ROWVERSION;
		
		private string _UNITVALUE2;
		
		public IOTRACKCOMPARE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDIOTRACK", DbType="Decimal(10,0) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal IDIOTRACK
		{
			get
			{
				return this._IDIOTRACK;
			}
			set
			{
				if ((this._IDIOTRACK != value))
				{
					this._IDIOTRACK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE", DbType="VarChar(4000)", UpdateCheck=UpdateCheck.Never)]
		public string MESSAGE
		{
			get
			{
				return this._MESSAGE;
			}
			set
			{
				if ((this._MESSAGE != value))
				{
					this._MESSAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATCHSTATUS", DbType="VarChar(64) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string MATCHSTATUS
		{
			get
			{
				return this._MATCHSTATUS;
			}
			set
			{
				if ((this._MATCHSTATUS != value))
				{
					this._MATCHSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTDATAID", DbType="Decimal(10,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> INTDATAID
		{
			get
			{
				return this._INTDATAID;
			}
			set
			{
				if ((this._INTDATAID != value))
				{
					this._INTDATAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTDATAIDS", DbType="VarChar(64)", UpdateCheck=UpdateCheck.Never)]
		public string INTDATAIDS
		{
			get
			{
				return this._INTDATAIDS;
			}
			set
			{
				if ((this._INTDATAIDS != value))
				{
					this._INTDATAIDS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXTDATAID", DbType="Decimal(10,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> EXTDATAID
		{
			get
			{
				return this._EXTDATAID;
			}
			set
			{
				if ((this._EXTDATAID != value))
				{
					this._EXTDATAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTVALUE1", DbType="Decimal(10,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> INTVALUE1
		{
			get
			{
				return this._INTVALUE1;
			}
			set
			{
				if ((this._INTVALUE1 != value))
				{
					this._INTVALUE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTVALUE2", DbType="Decimal(10,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> INTVALUE2
		{
			get
			{
				return this._INTVALUE2;
			}
			set
			{
				if ((this._INTVALUE2 != value))
				{
					this._INTVALUE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXTVALUE1", DbType="Decimal(10,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> EXTVALUE1
		{
			get
			{
				return this._EXTVALUE1;
			}
			set
			{
				if ((this._EXTVALUE1 != value))
				{
					this._EXTVALUE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXTVALUE2", DbType="Decimal(10,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> EXTVALUE2
		{
			get
			{
				return this._EXTVALUE2;
			}
			set
			{
				if ((this._EXTVALUE2 != value))
				{
					this._EXTVALUE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATCHVALUE1", DbType="Decimal(10,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> MATCHVALUE1
		{
			get
			{
				return this._MATCHVALUE1;
			}
			set
			{
				if ((this._MATCHVALUE1 != value))
				{
					this._MATCHVALUE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATCHVALUE2", DbType="Decimal(10,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> MATCHVALUE2
		{
			get
			{
				return this._MATCHVALUE2;
			}
			set
			{
				if ((this._MATCHVALUE2 != value))
				{
					this._MATCHVALUE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTINS", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DTINS
		{
			get
			{
				return this._DTINS;
			}
			set
			{
				if ((this._DTINS != value))
				{
					this._DTINS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAINS", DbType="Decimal(10,0) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal IDAINS
		{
			get
			{
				return this._IDAINS;
			}
			set
			{
				if ((this._IDAINS != value))
				{
					this._IDAINS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITVALUE1", DbType="VarChar(64)", UpdateCheck=UpdateCheck.Never)]
		public string UNITVALUE1
		{
			get
			{
				return this._UNITVALUE1;
			}
			set
			{
				if ((this._UNITVALUE1 != value))
				{
					this._UNITVALUE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWVERSION", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ROWVERSION
		{
			get
			{
				return this._ROWVERSION;
			}
			set
			{
				if ((this._ROWVERSION != value))
				{
					this._ROWVERSION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITVALUE2", DbType="VarChar(64)", UpdateCheck=UpdateCheck.Never)]
		public string UNITVALUE2
		{
			get
			{
				return this._UNITVALUE2;
			}
			set
			{
				if ((this._UNITVALUE2 != value))
				{
					this._UNITVALUE2 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
