#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFS.SpheresRiskPerformance.SpheresObjects
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RD_SPHERES_TST260")]
	public partial class TRADEMARGINTRACKDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    #endregion
		
		public TRADEMARGINTRACKDataContext() : 
				base(global::EFS.SpheresRiskPerformance.Properties.Settings.Default.RD_SPHERES_TST260ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public TRADEMARGINTRACKDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TRADEMARGINTRACKDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TRADEMARGINTRACKDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TRADEMARGINTRACKDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TRADEMARGINTRACK> TRADEMARGINTRACK
		{
			get
			{
				return this.GetTable<TRADEMARGINTRACK>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRADEMARGINTRACK")]
	public partial class TRADEMARGINTRACK
	{
		
		private decimal _IDT;
		
		private System.Nullable<decimal> _IDMARGINTRACK;
		
		private System.Xml.Linq.XElement _TRADEXML;
		
		private System.DateTime _DTINS;
		
		private decimal _IDAINS;
		
		private System.Data.Linq.Binary _ROWVERSION;
		
		public TRADEMARGINTRACK()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDT", DbType="Decimal(10,0) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal IDT
		{
			get
			{
				return this._IDT;
			}
			set
			{
				if ((this._IDT != value))
				{
					this._IDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMARGINTRACK", DbType="Decimal(10,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> IDMARGINTRACK
		{
			get
			{
				return this._IDMARGINTRACK;
			}
			set
			{
				if ((this._IDMARGINTRACK != value))
				{
					this._IDMARGINTRACK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRADEXML", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement TRADEXML
		{
			get
			{
				return this._TRADEXML;
			}
			set
			{
				if ((this._TRADEXML != value))
				{
					this._TRADEXML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTINS", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DTINS
		{
			get
			{
				return this._DTINS;
			}
			set
			{
				if ((this._DTINS != value))
				{
					this._DTINS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAINS", DbType="Decimal(10,0) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal IDAINS
		{
			get
			{
				return this._IDAINS;
			}
			set
			{
				if ((this._IDAINS != value))
				{
					this._IDAINS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWVERSION", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ROWVERSION
		{
			get
			{
				return this._ROWVERSION;
			}
			set
			{
				if ((this._ROWVERSION != value))
				{
					this._ROWVERSION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
